apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: john-developer
spec:
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1ZEQ0NBVHdDQVFBd0R6RU5NQXNHQTFVRUF3d0VhbTlvYmpDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRApnZ0VQQURDQ0FRb0NnZ0VCQUxNSDB1alF0VSt1cmZDL08xYWdsRUlxQVFWS1pSTGFZQyswL2dEaU1ab1NEL2wrClJqVGQ1emFOQzZiWEl2b3h0Rm84NEhEK2U1VUIzUGJsdUd6TU1RdGJzYmhRcWcvYThXVkFVSnNBckNhKzF2UlAKV25wVnZabCs4bmQ3S0dsYk1vVktTdVppTkIxRzA4a2VRMW1kTlJrT2dUK3k3T0FoZmZTQUxUa0JQeHFZdDBTdQp2YjhGMHBTNVZtSDdMS3lscG5ENWhxZm9zTFpYWmNUMTFPUVhhaSs1UDRDbW9xUjJtR2hFNXlJK1FoUTlNbTIyCmpORDRvRmZzT3YzeXdoSjZJZ09yWngzVENLWU1NUUY4MGJyWUpUTzlJUFVBNExMKy90cVAxZ2ZhcGdpUzQ2enMKL2FKT2x0VXVGbzEwdy82VUxaOWk0SWZpcU9WaytLeERCZlFGcUxzQ0F3RUFBYUFBTUEwR0NTcUdTSWIzRFFFQgpDd1VBQTRJQkFRQlRuTEhJcWRudXBPZUZBMmhQb1htSzBvM1lLciszMlVPWXNWOVNCejRnSUZxMWFXcFZLMTVBCm9VWEpmdklZMmJEUlkxYlJ0ckpZaC8xdmVVQ08zSkVJdDBMajFOdEMydDdiOG04YVFpMUlYT2ZMcjEzVCtoc0oKNzh2Y2JjM0RoN1cyYjEwc1VQdmF0SDExZzBKUTE5U2VqUmNLWGcvOWk5d1ZsckxicHVPelFOTW53OTFnUU5XSApIQ2hhZGM5Q01naHNLTi9rbC9qNUFuRVh0MXRhSnhYTU1CNHNLYVFja254STUwOGNiN2FKZDVHUkVFOUEybWVxCm1OTlNRNW5Neko0Y0NjdEYyUWRSRWo5NXI5Tk14d1ZJU0JnaDQ1Nlg5Q05GN0IvOFRlaUg2bHlwZ0p1cjk4WCsKNFlUbWR5ajJZV2pHdDV5UkJ4dm9OVjVrSFNnS3ZiMWUKLS0tLS1FTkQgQ0VSVElGSUNBVEUgUkVRVUVTVC0tLS0tCg==
  signerName: kubernetes.io/kube-apiserver-client
  usages:
    - digital signature
    - key encipherment
    - client auth
